### ISSUE TITLE
Configuration missing

### ISSUE THREAD

**Issue by Ailurupoda** [3liz/lizmap-docker-compose#1]
Hi,

Using this docker-compose file, i manage to have a lizmap working pretty well.
My problem is the lack of information on the lizmap config panel. 
I only see few of the parameters. For exemple, the WMS server url is missing as well as the cache storage.
Is their a way to show those information and manage them ?

Thanks by advance

**Comment by dmarteau** [comment]
Hi,

If your refer to the lizmap web client configuration panel, then WMS server URL and cache storage are admin/server side only configuration, for security reasons, they are not supposed to be exposed to config panel.

**Comment by Ailurupoda** [comment]
So the parameters are set in the dockerfile directly and not editable after, right  ?

**Comment by dmarteau** [comment]
No, they are configurable from the container env variables at runtime: `LIZMAP_WMSSERVERURL` ...
You may have a look to https://github.com/3liz/docker-lizmap-web-client for a description of the configuration variables.

**Comment by Ailurupoda** [comment]
Thanks
