### ISSUE TITLE
How / Where to find script php for caching tiles ?

### ISSUE THREAD

**Issue by Doctor-Who** [3liz/lizmap-docker-compose#11]
Hi,

I'm using this docker-compose but I cannot find any mountpoint to access to the var/www/lizmap-web-client/
How to execute lizmap/scripts/script.php to generate tiles for wmts ? 

Also command docker exec -it lizmap bash is not working on this container.

Thanks for helping me :)

**Comment by Doctor-Who** [comment]
My bad guys...

`docker exec -it lizmap_lizmap bash `not working but `docker exec -it lizmap_lizmap sh` works

**Comment by dmarteau** [comment]
> docker exec -it lizmap_lizmap bash not working but docker exec -it lizmap_lizmap sh works

The Lizmap image is based on `alpine` linux distro so `bash` is not installed.
