### ISSUE TITLE
How can I use certbot and redirect 8090 to 443 with subdomain name ?

### ISSUE THREAD

**Issue by Youssef-Harby** [3liz/lizmap-docker-compose#16]
How can I use certbot and redirect 8090 to 443 with subdomain name?
Thanks!

**Comment by dmarteau** [comment]
You have to change the nginx configuration. 

Note: this is a sample configuration for testing Lizmap web client with QGIS: 
if you want use it on a production server you will need to make adjustments for meeting your production requirements.

**Comment by Youssef-Harby** [comment]
I only need this testing docker for my graduation project, can you help me with sample Nginx Configuration?
`lizmap-docker-compose\lizmap\etc\nginx.conf`

**Comment by dmarteau** [comment]
You may have a look at http://nginx.org/en/docs/http/configuring_https_servers.html
