### ISSUE TITLE
Can't activate "edition" mode

### ISSUE THREAD

**Issue by katagen** [3liz/lizmap-docker-compose#18]
Hello,
I created a QGIS projet, with only an orthophoto and a Spatialite layer (points).
I can't activate the "edition" mode in my Lizamp client web.

I can see the orthophoto, also see the point layer, check the attribute table... But I can't find the way to add new points, or delete them?!?

In QGIS, server option, I checked the WFS to be editable in update, delete and add. I also have a primary key.
In Lizamp plugin, I selected the layer, checked "create", "edit attribute" "delete" and " edit geometry". I aslo gave permission to the "users" group.
In Lizmap admin panel, I give permissions to update the layer to the "users" group.

But I see nowhere the "edition" tool?
Did I something wrong?

**Comment by dmarteau** [comment]
That's seems to be more a lizmap issue than a docker issue. You should consider addressing the problem here: https://github.com/3liz/lizmap-web-client

**Comment by katagen** [comment]
Not sure, depends if the php for sqlite is activated!
https://docs.lizmap.com/current/en/

**Comment by ygorigor** [comment]
https://github.com/3liz/lizmap-plugin/pull/364

**Comment by Gustry** [comment]
As mentioned by @ygorigor, the spatialite editing capabilities has been disabled in the lizmap QGIS plugin.
