### ISSUE TITLE
Use the new environment variable for LWC 3.5

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-docker-compose#22]
Since LWC 3.5.1-pre, we need a new environment variable for QGIS Server to enable the plugins versions in the administration panel, and add the API entrypoint for the pyqgisserver.
CF https://docs.lizmap.com/current/en/install/pre_requirements.html#lizmap-server-plugin

**Comment by Gustry** [comment]
I don't know how to enable the Lizmap API URL in this docker-compose project.

**Comment by dmarteau** [comment]
The lizmap API url must be accessed from LWC ? It can be done either from managment port (no configuration needed) or from the default exposed port (configuration needed in config file). 

Afaik, access to managment port was implemented in LWC, no ?

**Comment by Gustry** [comment]
Everything is in the documentation : https://docs.lizmap.com/current/en/install/pre_requirements.html#installation
There is the setting in Py-QGIS-Server.
