### ISSUE TITLE
[ARM64] exec user process caused: exec format error

### ISSUE THREAD

**Issue by jlstanus** [3liz/lizmap-docker-compose#23]
Hi,

I'm using the odroid-C2 with 16gb ssd with ubuntu 20.04 minimal image.
I'have the following issue after pulling the images.
The start up meets an error: exec user process caused: exec format error

![image](https://user-images.githubusercontent.com/402354/161773388-c7eef96d-a66a-4890-85d3-b31572550da9.png)

**Comment by dmarteau** [comment]
There is no prebuilt image for ARM arch.  If you want ARM support you must go throught the [multiarch build process](https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images).

**Comment by jlstanus** [comment]
So i need to go to each service to try to build it's own image with --plateform linux/arm64 and refer it in the docker-compose file?

**Comment by dmarteau** [comment]
That's the idea.
