### ISSUE TITLE
Use qgis-lizmap-server-plugin instead of Lizmap plugin

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-docker-compose#26]

**Comment by Gustry** [comment]
This ticket is highly linked to #22 because the new the Lizmap plugin does not include the server part and needs the environment variable to make LWC 3.5 working.

**Comment by dmarteau** [comment]
The Qgis server image provide qgis-plugin-manager since the release of py-qgis-server 1.8.1
