### ISSUE TITLE
Time Manager Animation Date in Descending Order 

### ISSUE THREAD

**Issue by ocastillog** [3liz/lizmap-docker-compose#38]
Hello guys:

I'm testing the Time Manager component in Lizmap and it's working great. My question is, there's an option for animate with the date attribute in descending order, starting on max date to min date?

Thanks in advance,
Osmin Castillo

**Comment by Gustry** [comment]
Sorry for the delay, but this kind of request should go in the main Lizmap Web Client github repository.
