### ISSUE TITLE
Test projects are not visible

### ISSUE THREAD

**Issue by laurascasse** [3liz/lizmap-docker-compose#46]
After a lot of difficulties during setup, i'm finally running lizmap with docker desktop on windows
But i don't see the tests projects situated in \lizmap\instances

In the administration panel, the root for repository is /srv/ i've also tried /srv/projects  for same result
I miss a step ?
Thanks

![image](https://user-images.githubusercontent.com/88839452/220850470-ab407e96-e609-4c2b-aa10-99736f26ea13.png)
![image](https://user-images.githubusercontent.com/88839452/220850572-e5f86c4f-3d34-43a8-8d85-9f255f6a4a47.png)

**Comment by nworr** [comment]
By default, the root folder for repository is /srv/projects/ (binded to your local <docker compots folder>/lizmap/instances).

Then in "Map Management" section , you need to create a repository related to existing folder (relative to root folder) and allow users to view projects 

![image](https://github.com/3liz/lizmap-docker-compose/assets/43475951/374781eb-ff88-4283-80c9-7fd5636ec6c1)
 
Then the repository and the projects should be visible in the project page

![image](https://github.com/3liz/lizmap-docker-compose/assets/43475951/b053b11b-510c-4ef7-ac49-b3fb08bdd704)

**Comment by Gustry** [comment]
Is this issue still relevant ?

**Comment by laurascasse** [comment]
I don't i can't test it anymore, i think you can close.
