### ISSUE TITLE
lizmap projects

### ISSUE THREAD

**Issue by indeOWS** [3liz/lizmap-docker-compose#5]
I have started a lizmap instance with the following setup:

export LIZMAP_DIR=${LIZMAP_DIR:-/home/geo/Documents/projects/qgis/lizmap}
export LIZMAP_USER_ID=${LIZMAP_USER:-$(id -u)} 
export LIZMAP_USER_GID=${LIZMAP_GID:-$(id -g)}

According to this config LIZMAP_USER_ID = 1000 and LIZMAP_USER_GID=1000
I have qgis qgs and shapefiles in ${LIZMAP_DIR}/instances. I also have configured qgis lizmap plugin and qgis-server, but when I started lizmap http://localhost:8888 I could not find qgis projects.

**Comment by nboisteault** [comment]
@indeOWS Did you finally resolve your issue?

**Comment by nboisteault** [comment]
Please reopen if issue still occurs.
