### ISSUE TITLE
Install lizmap with docker compose on a server

### ISSUE THREAD

**Issue by jayeffe** [3liz/lizmap-docker-compose#57]
I tried installing lizmap with docker compose on an ubuntu machine. In the desktop version I can log in to localhost. I'm trying to connect with 0.0.0.0 so as to simulate connecting from outside the machine (like a server)

I changed the pointing to LIZMAP_PORT=${LIZMAP_PORT:-"127.0.0.1:8090"} by entering 0.0.0.0 instead of 127.0.0.1

When I connect from the outside, I can see the login form, in a minimal version without graphics. I log in and see the lizmap page but as soon as I click it gives me 500 errors

How can I solve it? I would also like to have a secure server setup

COPY_COMPOSE_FILE=0
LIZMAP_VERSION_TAG=${LIZMAP_VERSION_TAG:-"3.5"}
QGIS_VERSION_TAG=${QGIS_VERSION_TAG:-"3.22"}
POSTGIS_VERSION=${POSTGIS_VERSION:-"13-3"}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-"postgres"}
POSTGRES_LIZMAP_DB=${POSTGRES_LIZMAP_DB:-"lizmap"}
POSTGRES_LIZMAP_USER=${POSTGRES_LIZMAP_USER:-"lizmap"}
POSTGRES_LIZMAP_PASSWORD=${POSTGRES_LIZMAP_PASSWORD:-"lizmap1234!"}
QGIS_MAP_WORKERS=${QGIS_MAP_WORKERS:-"1"}
WPS_NUM_WORKERS=${WPS_NUM_WORKERS:-"1"}
LIZMAP_PORT=${LIZMAP_PORT:-"127.0.0.1:8090"}
OWS_PORT=${OWS_PORT:-"127.0.0.1:8091"}
WPS_PORT=${WPS_PORT:-"127.0.0.1:8092"}
POSTGIS_PORT=${POSTGIS_PORT:-"127.0.0.1:5432"}
POSTGIS_ALIAS=${POSTGIS_ALIAS:-"db.lizmap"}

**Comment by dmarteau** [comment]
>  but as soon as I click it gives me 500 errors

The logs  ouptut should provides you with some details about the error.

>  I would also like to have a secure server setup

This is a system admininistrator task: to be short, the only entry point from the outside should be the nginx as reverse proxy with the appropriate ssl/tls configuration.

I would like to emphasize, as noted in the readme,  "this is a sample configuration for testing Lizmap web client with QGIS and WPS features". You'll need to make the proper adjustement and configuration to meet your security/operational requirements - see https://github.com/3liz/lizmap-docker-compose/issues/56#issuecomment-1715808190 for some hints about how to achieve this.

**Comment by Gustry** [comment]
> When I connect from the outside, I can see the login form, in a minimal version without graphics. 

What the status of these HTTP requests ?

> I log in and see the lizmap page but as soon as I click it gives me 500 errors

Please check your logs of the web server, `docker logs` command.

**Comment by jayeffe** [comment]
As I understand it, only nginx interfaces with the outside right?
so do I need a reverse proxy to access from outside?
