### ISSUE TITLE
Production server requirements

### ISSUE THREAD

**Issue by jayeffe** [3liz/lizmap-docker-compose#59]
I was trying to install on a server.
Currently I have exposed, by modifying the docker-compose.yml, port 5432 and the lizmap port. It's enough?
What other operations can I do?.

I wanted to understand whether to modify this configuration provided

`  server {
        listen 8080;

       server_name lizmap;

        root /srv/lizmap/www;
        index index.html index.php;

        access_log /var/log/nginx/lizmap_access.log;
        error_log /var/log/nginx/lizmap_error.log;

        # URI resolved to web sub directory
        # and found a index.php file here
        location ~* /(\w+/)?\w+\.php {

            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            set $path_info $fastcgi_path_info; # because of bug http://trac.nginx.org/nginx/ticket/321

            try_files $fastcgi_script_name =404;
            include fastcgi_params;

            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param SERVER_NAME $http_host;
            fastcgi_param PATH_INFO $path_info;
            fastcgi_param PATH_TRANSLATED $document_root$path_info;
            fastcgi_pass  lizmap:9000;
        }
    }

`

**Comment by Gustry** [comment]
The configuration only depends on **your own** production requirements.

I'm closing as there isn't any "right" answer.
