### ISSUE TITLE
Lizmap Docker running under traefik?

### ISSUE THREAD

**Issue by LucaMoiana** [3liz/lizmap-docker-compose#6]
Hi,
I know this is not an issue,
I'm trying to run lizmap-docker under traefik 1.7:
I did add some labels to the nignx docker:

```
      - traefik.enable: "true"
      - traefik.backend: "lizmap"
      - traefik.frontend.rule: "Host: lizmap.officinecartografiche.net"
      - traefik.port=8080
      -  traefik.docker.network: "web"
```
But that's not enough and I keep getting a niginx.conf error. 
Can you point me to some configuration example or tutorial?
thanks for your help and your great development

**Comment by dmarteau** [comment]
AMHA, it seems more a traefik issue than a Lizmap stack issue.

**Comment by LucaMoiana** [comment]
I know, I just wanted to know if, by any chance, you had some example.

**Comment by dmarteau** [comment]
No, I do not use traefik.
