### ISSUE TITLE
QGIS server : cp: cannot stat '/srv/etc/qgis/*': No such file or directory

### ISSUE THREAD

**Issue by jfoucher** [3liz/lizmap-docker-compose#62]
After following the readme to the letter, this repository does not work : 

```
lizmap-docker-compose-map-1      | Running as 1000:1000
lizmap-docker-compose-map-1      | Running Xvfb
lizmap-docker-compose-map-1      | Copying Qgis configuration: /srv/etc/qgis
lizmap-docker-compose-map-1      | cp: cannot stat '/srv/etc/qgis/*': No such file or directory
lizmap-docker-compose-map-1 exited with code 1
```

Other containers work fine.
Anything I can do ?

**Comment by dmarteau** [comment]
Where does `/srv/etc/qgis` come from ?

**Comment by jfoucher** [comment]
https://github.com/3liz/lizmap-docker-compose/blob/5261ae7740a7a158af065a1283c179891e440093/docker-compose.yml#L51

**Comment by dmarteau** [comment]
The ${LIZMAP_DIR}/etc/qgis directory is missing, create it manually for a quick fix or remove the QGIS_OPTIONS_PATH from the service environment variables.

**Comment by jfoucher** [comment]
`mkdir lizmap/etc/qgis && touch lizmap/qgis/a && docker compose up` seems to work.

Do you want me to close this issue now @Gustry ?

**Comment by Gustry** [comment]
Me ? :) I don't know, it depends where the error comes from. I will let @dmarteau

**Comment by dmarteau** [comment]
There is a small fix to do before closing the issue.

**Comment by laurentj** [comment]
I fixed it.
