### ISSUE TITLE
lizmap/www directory not created

### ISSUE THREAD

**Issue by MarLoi** [3liz/lizmap-docker-compose#63]
For a few days now, running ./configure.sh configure does not create the /lizmap/www directory

**Comment by laurentj** [comment]
I found the commit, I'm going to fix the issue.

**Comment by laurentj** [comment]
It is fixed. It was a regression after fixing a security issue. You should remove the directory `www/var/log` if it exists.

**Comment by MarLoi** [comment]
👌
