### ISSUE TITLE
Proper way to update lizmap version

### ISSUE THREAD

**Issue by lucadelu** [3liz/lizmap-docker-compose#69]
Hi, 

I would like to update my Lizmap version from 3.6 to 3.7, I read the [documentation](https://docs.lizmap.com/current/en/install/upgrade.html) about it, I would like to know if using docker-compose the steps written in the documentation are needed or if the container is doing it.

Thanks a lot.

**Comment by undertaker12** [comment]
i use docker compose if u change in @env file to 3.7 just pull and up

**Comment by lucadelu** [comment]
ok, I tried and it seems to work properly
