### ISSUE TITLE
URL Qgis Server not correct

### ISSUE THREAD

**Issue by ericgis** [3liz/lizmap-docker-compose#71]
dans le compose avec le qgis-serveur 3.34, lizmap indique une url non correct. Pas de problème avec l'image qgis serveur 3.28

**Comment by Gustry** [comment]
What is the error message ? How did you setup your containers ?
I don't replicate the issue with QGIS server 3.34.

**Comment by ericgis** [comment]
I forgot to update plugins based on server version
thx !
