### ISSUE TITLE
Value Map values appear empty when re-editing

### ISSUE THREAD

**Issue by abodsalas** [3liz/lizmap-docker-compose#75]
Good day.
I am having issues with the “Value Map” option in the Attribute Forms of a PostgreSQL layer.
 
![image](https://github.com/user-attachments/assets/72bc8212-172c-4e20-9975-65c36ec96dc7)

I can create a line, and assign values from a Value Map. I save the complete form and the Popup shows the correct value. The fields with “Value Map” categories are “Cate” and “Categoria”.

![image](https://github.com/user-attachments/assets/cbaccc22-3245-49cf-895f-067fc39298cf)

The issue arises when I edit the saved line.
The Popup shows “Cate” and “Categoria” as EMPTY:

![image](https://github.com/user-attachments/assets/bc013142-ef9e-4563-a574-828d46f3e339)

If I edit another field like the Date and Save, “Cate” and “Categoria” are saved as empty.
I have other projects in the same Lizmap platform where everything works correctly. However, I cannot find the difference that could explain why this happens.

**The information of my setup is:**
**Information, Lizmap Web Client:**
Version: 3.6.14
Date: 2024-07-04
URL in the QGIS desktop plugin: http://10.20.1.12:8080/
Information, QGIS Server:
Number: 3.28.13
Name: Firenze
Information, Plugins:
atlasprint: 3.4.1
Lizmap server: 2.9.4
wfsOutputExtension: 1.8.0

**Steps to reproduce the issue**
Create a line layer using PostgreSQL, configure a field with Value Map in the Attribute Form.
Publish the map, assign values to the field and Save.
Edit the line, and the Value Map attribute appears Empty.

**Versions, safeguards, check summary etc
Versions :**
•	Lizmap Web Client : 3.6.14
•	Lizmap plugin : 4.3.21
•	QGIS Desktop : 3.28.13
•	QGIS Server : 3.28.13
•	Py-QGIS-Server : 1.8.8
•	QGIS Server plugin atlasprint : 3.4.1
•	QGIS Server plugin lizmap_server : 2.9.4
•	QGIS Server plugin wfsOutputExtension : 1.8.0

List of safeguards :
Check Lizmap plugin
•	  I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

**Comment by Gustry** [comment]
Hi, sorry I'm closing this issue.
Lizmap Web Client 3.6 is not maintained anymore, please try again on Lizmap Web Client 3.8.
And this bug tracker is about the docker-compose project.
